Add support for insulin, physicalActivity and reportedState (BACK-1810)
tidepool-org/jellyfish pull request #132
Opened 2020-11-10 15:14 UTC by gniezen

Addresses [BACK-1810].

2020-11-12 03:29 UTC, pazaan requested changes
Suggestions to match `platform` behaviour.

2020-11-12 03:29 UTC, pazaan commented on lib/schema/physicalActivity.js
> +      value: schema.isNumber,
This doesn't quite [match the behaviour in platform](https://github.com/tidepool-org/platform/blob/25bfa5aaf9702b1d6a0eebe08798285c33868183/data/types/activity/physical/duration.go#L60-L72), which has more validation around the values depending on the units. If we wanted to replicate this behaviour, we may have to do a higher-level `schema.or`.

2020-11-12 03:29 UTC, pazaan commented on lib/schema/reportedState.js
> +  state: schema.isString
In `platform`, there are a [few fixed states](https://github.com/tidepool-org/platform/blob/25bfa5aaf9702b1d6a0eebe08798285c33868183/data/types/state/reported/state.go#L14-L18) (ie, `state` must be one of the fixed states). If the state is anything other than one of the fixed states, then `state` should be "other", and an additional field called `stateOther` should exist, with a string of maximum length 100.
If you wanted to replicate this as simply as possible, you could do it like this:
```
var stateArraySchema = schema.isArrayWithValueSchema({
  state: schema.in('other'),
  stateOther: schema.isStringOfMaxLength(100)
});
```

2020-11-18 01:29 UTC, pazaan submitted a review, later dismissed
LGTM! :shipit:

2020-12-02 14:35 UTC, gniezen commented
/deploy qa2

2020-12-02 14:49 UTC, gniezen commented
@tjotala Would you mind just re-approving this PR now that Lennart doesn't have write access anymore?

2020-12-02 14:55 UTC, toddkazakov submitted a review, later dismissed

2020-12-02 15:16 UTC, gniezen commented
Will need to deploy to QA1, as that's where the test accounts were made.

2020-12-02 15:17 UTC, gniezen commented
/deploy qa1

2021-02-03 12:58 UTC, toddkazakov approved these changes
LGTM

2021-02-25 09:53 UTC, merged