[BACK-1746] Convert string dates to ISODATE in DB
tidepool-org/jellyfish pull request #141
Opened 2021-08-24 18:24 UTC by Roukoswarf

This has been tested using uploader and postman APITests along with manual testing, and covers all found cases using string dates.
Unit tests will most likely fail for now, as they manually specify date strings, and I believe it will be best to gather feedback on the approach, and discuss unit testing strategies before adjusting them.

2021-08-30 15:28 UTC, toddkazakov requested changes
`updateDatumInternal` needs to be updated so it uses dates instead of strings

2021-08-30 15:50 UTC, toddkazakov requested changes
`getDatumBefore` might also fail, because it doesn't filter by either `string` or `Date` time.

2021-09-07 19:49 UTC, Roukoswarf commented
> `getDatumBefore` might also fail, because it doesn't filter by either `string` or `Date` time.

this should work, as its using the next record to find the previous, and that type would change dynamically, dates always sort after strings, so this should work even with mixed data.

2021-09-09 13:58 UTC, toddkazakov commented on lib/streamDAO.js
> +    if ('time' in datum && typeof(datum.time) === 'string') {
This code is called when inserting or updating a datum. I believe deduplication will not work correctly if you first update a datum, then you try to reinsert the same one (with identical identity fields). Update doesn't change `id` and `_id` which are already generated based on the original string value of a date. When inserting a new one, you'll end up generating a new `id` and `_id` based on native date times, which will generate a different hash.

2021-09-09 14:04 UTC, toddkazakov commented
There seems to be a problem when generating `basal.nextId`, which is also apparent from the failing unit tests. I don't exactly know what the problem is, without actually fixing it myself. The code is very difficult to follow.

2021-09-09 14:39 UTC, toddkazakov commented
See `schema/schema.js#decepticon()`:
```js
function decepticon(datum, cb) {
    if (datum._userId == null) {
      return cb(new Error('_userId must be set on a datum'));
    }
    if (datum._groupId == null) {
      return cb(new Error('_groupId must be set on a datum'));
    }

    if (datum.time[datum.time.length - 1] !== 'Z') {
      datum.time = new Date(datum.time).toISOString();
    }

    try {
      transformer(datum, function(err, newDatum){
        if (err != null) {
          return cb(err);
        }
        var withId = attachId(newDatum);

        // Swap out cb so that we don't call it again if it throws out an error
        var theCallback = cb;
        cb = function(err) { if (err != null) { throw err; } };
        theCallback(null, withId);
      });
    } catch (e) {
      if (e.type === 'IllegalArgumentException') {
        e.statusCode = 400;
      }
      return cb(e);
    }
  }
```

This function wraps the transformer functions and in some cases might modify the time so it's set to a string value.

2021-10-13 15:18 UTC, toddkazakov requested changes
Like we discussed few weeks ago on Slack, I believe you should convert the time keys back to strings right after they are fetched from the db to avoid changing any logic that relies on time attributes being strings (e.g. deduplication logic that includes the `time` attribute in the `_id` of the datum). I'm not sure this is a valid concern, but it feels like this is the right thing to do given that any issues with deduplication might go unnoticed.

Left some inline comments which also need to be addressed before this is ready for testing.

2021-10-13 15:18 UTC, toddkazakov commented on lib/streamDAO.js
> +	  entry = entry.suppressed;
Should you convert dates in `datum.previous` the same you convert them in `datum.suspended`?

2021-10-13 15:18 UTC, toddkazakov commented on lib/streamDAO.js
>      var clone = _.clone(datum);
Should you replace any time fields which are strings with native dates here?

2021-12-22 19:50 UTC, ginnyyadav commented
/deploy qa1

2022-04-15 09:24 UTC, toddkazakov approved these changes

2022-09-22 16:32 UTC, merged